//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.0.
// 
#pragma warning disable 1591

namespace testbed.uk.co.nationalrail.realtime.lite {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LDBServiceSoap", Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/")]
    public partial class ldb : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AccessToken accessTokenValueField;
        
        private System.Threading.SendOrPostCallback GetDepartureBoardOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetArrivalBoardOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetArrivalDepartureBoardOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServiceDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ldb() {
            this.Url = global::testbed.Properties.Settings.Default.testbed_uk_co_nationalrail_realtime_lite_ldb;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AccessToken AccessTokenValue {
            get {
                return this.accessTokenValueField;
            }
            set {
                this.accessTokenValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDepartureBoardCompletedEventHandler GetDepartureBoardCompleted;
        
        /// <remarks/>
        public event GetArrivalBoardCompletedEventHandler GetArrivalBoardCompleted;
        
        /// <remarks/>
        public event GetArrivalDepartureBoardCompletedEventHandler GetArrivalDepartureBoardCompleted;
        
        /// <remarks/>
        public event GetServiceDetailsCompletedEventHandler GetServiceDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AccessTokenValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://thalesgroup.com/RTTI/2012-01-13/ldb/GetDepartureBoard", RequestElementName="GetDepartureBoardRequest", RequestNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", ResponseNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetStationBoardResult")]
        public StationBoard GetDepartureBoard(ushort numRows, string crs, string filterCrs, [System.ComponentModel.DefaultValueAttribute(FilterType.to)] FilterType filterType, [System.ComponentModel.DefaultValueAttribute(0)] int timeOffset, [System.ComponentModel.DefaultValueAttribute(120)] int timeWindow) {
            object[] results = this.Invoke("GetDepartureBoard", new object[] {
                        numRows,
                        crs,
                        filterCrs,
                        filterType,
                        timeOffset,
                        timeWindow});
            return ((StationBoard)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartureBoardAsync(ushort numRows, string crs, string filterCrs, FilterType filterType, int timeOffset, int timeWindow) {
            this.GetDepartureBoardAsync(numRows, crs, filterCrs, filterType, timeOffset, timeWindow, null);
        }
        
        /// <remarks/>
        public void GetDepartureBoardAsync(ushort numRows, string crs, string filterCrs, FilterType filterType, int timeOffset, int timeWindow, object userState) {
            if ((this.GetDepartureBoardOperationCompleted == null)) {
                this.GetDepartureBoardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartureBoardOperationCompleted);
            }
            this.InvokeAsync("GetDepartureBoard", new object[] {
                        numRows,
                        crs,
                        filterCrs,
                        filterType,
                        timeOffset,
                        timeWindow}, this.GetDepartureBoardOperationCompleted, userState);
        }
        
        private void OnGetDepartureBoardOperationCompleted(object arg) {
            if ((this.GetDepartureBoardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartureBoardCompleted(this, new GetDepartureBoardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AccessTokenValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://thalesgroup.com/RTTI/2012-01-13/ldb/GetArrivalBoard", RequestElementName="GetArrivalBoardRequest", RequestNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", ResponseNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetStationBoardResult")]
        public StationBoard GetArrivalBoard(ushort numRows, string crs, string filterCrs, [System.ComponentModel.DefaultValueAttribute(FilterType.to)] FilterType filterType, [System.ComponentModel.DefaultValueAttribute(0)] int timeOffset, [System.ComponentModel.DefaultValueAttribute(120)] int timeWindow) {
            object[] results = this.Invoke("GetArrivalBoard", new object[] {
                        numRows,
                        crs,
                        filterCrs,
                        filterType,
                        timeOffset,
                        timeWindow});
            return ((StationBoard)(results[0]));
        }
        
        /// <remarks/>
        public void GetArrivalBoardAsync(ushort numRows, string crs, string filterCrs, FilterType filterType, int timeOffset, int timeWindow) {
            this.GetArrivalBoardAsync(numRows, crs, filterCrs, filterType, timeOffset, timeWindow, null);
        }
        
        /// <remarks/>
        public void GetArrivalBoardAsync(ushort numRows, string crs, string filterCrs, FilterType filterType, int timeOffset, int timeWindow, object userState) {
            if ((this.GetArrivalBoardOperationCompleted == null)) {
                this.GetArrivalBoardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArrivalBoardOperationCompleted);
            }
            this.InvokeAsync("GetArrivalBoard", new object[] {
                        numRows,
                        crs,
                        filterCrs,
                        filterType,
                        timeOffset,
                        timeWindow}, this.GetArrivalBoardOperationCompleted, userState);
        }
        
        private void OnGetArrivalBoardOperationCompleted(object arg) {
            if ((this.GetArrivalBoardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArrivalBoardCompleted(this, new GetArrivalBoardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AccessTokenValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://thalesgroup.com/RTTI/2012-01-13/ldb/GetArrivalDepartureBoard", RequestElementName="GetArrivalDepartureBoardRequest", RequestNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", ResponseNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetStationBoardResult")]
        public StationBoard GetArrivalDepartureBoard(ushort numRows, string crs, string filterCrs, [System.ComponentModel.DefaultValueAttribute(FilterType.to)] FilterType filterType, [System.ComponentModel.DefaultValueAttribute(0)] int timeOffset, [System.ComponentModel.DefaultValueAttribute(120)] int timeWindow) {
            object[] results = this.Invoke("GetArrivalDepartureBoard", new object[] {
                        numRows,
                        crs,
                        filterCrs,
                        filterType,
                        timeOffset,
                        timeWindow});
            return ((StationBoard)(results[0]));
        }
        
        /// <remarks/>
        public void GetArrivalDepartureBoardAsync(ushort numRows, string crs, string filterCrs, FilterType filterType, int timeOffset, int timeWindow) {
            this.GetArrivalDepartureBoardAsync(numRows, crs, filterCrs, filterType, timeOffset, timeWindow, null);
        }
        
        /// <remarks/>
        public void GetArrivalDepartureBoardAsync(ushort numRows, string crs, string filterCrs, FilterType filterType, int timeOffset, int timeWindow, object userState) {
            if ((this.GetArrivalDepartureBoardOperationCompleted == null)) {
                this.GetArrivalDepartureBoardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArrivalDepartureBoardOperationCompleted);
            }
            this.InvokeAsync("GetArrivalDepartureBoard", new object[] {
                        numRows,
                        crs,
                        filterCrs,
                        filterType,
                        timeOffset,
                        timeWindow}, this.GetArrivalDepartureBoardOperationCompleted, userState);
        }
        
        private void OnGetArrivalDepartureBoardOperationCompleted(object arg) {
            if ((this.GetArrivalDepartureBoardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArrivalDepartureBoardCompleted(this, new GetArrivalDepartureBoardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AccessTokenValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://thalesgroup.com/RTTI/2012-01-13/ldb/GetServiceDetails", RequestElementName="GetServiceDetailsRequest", RequestNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", ResponseNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceDetails GetServiceDetails(string serviceID) {
            object[] results = this.Invoke("GetServiceDetails", new object[] {
                        serviceID});
            return ((ServiceDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceDetailsAsync(string serviceID) {
            this.GetServiceDetailsAsync(serviceID, null);
        }
        
        /// <remarks/>
        public void GetServiceDetailsAsync(string serviceID, object userState) {
            if ((this.GetServiceDetailsOperationCompleted == null)) {
                this.GetServiceDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceDetailsOperationCompleted);
            }
            this.InvokeAsync("GetServiceDetails", new object[] {
                        serviceID}, this.GetServiceDetailsOperationCompleted, userState);
        }
        
        private void OnGetServiceDetailsOperationCompleted(object arg) {
            if ((this.GetServiceDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceDetailsCompleted(this, new GetServiceDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2013-11-28/Token/types")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://thalesgroup.com/RTTI/2013-11-28/Token/types", IsNullable=false)]
    public partial class AccessToken : System.Web.Services.Protocols.SoapHeader {
        
        private string tokenValueField;
        
        /// <remarks/>
        public string TokenValue {
            get {
                return this.tokenValueField;
            }
            set {
                this.tokenValueField = value;
            }
        }

        public static implicit operator AccessToken(string v)
        {
            throw new NotImplementedException();
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2012-01-13/ldb/types")]
    public partial class CallingPoint {
        
        private string locationNameField;
        
        private string crsField;
        
        private string stField;
        
        private string etField;
        
        private string atField;
        
        private string[] adhocAlertsField;
        
        /// <remarks/>
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        public string crs {
            get {
                return this.crsField;
            }
            set {
                this.crsField = value;
            }
        }
        
        /// <remarks/>
        public string st {
            get {
                return this.stField;
            }
            set {
                this.stField = value;
            }
        }
        
        /// <remarks/>
        public string et {
            get {
                return this.etField;
            }
            set {
                this.etField = value;
            }
        }
        
        /// <remarks/>
        public string at {
            get {
                return this.atField;
            }
            set {
                this.atField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("adhocAlertText")]
        public string[] adhocAlerts {
            get {
                return this.adhocAlertsField;
            }
            set {
                this.adhocAlertsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/types")]
    public partial class ArrayOfCallingPoints {
        
        private CallingPoint[] callingPointField;
        
        private ServiceType serviceTypeField;
        
        private bool serviceTypeFieldSpecified;
        
        private bool serviceChangeRequiredField;
        
        private bool serviceChangeRequiredFieldSpecified;
        
        private bool assocIsCancelledField;
        
        private bool assocIsCancelledFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("callingPoint", IsNullable=true)]
        public CallingPoint[] callingPoint {
            get {
                return this.callingPointField;
            }
            set {
                this.callingPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ServiceType serviceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serviceTypeSpecified {
            get {
                return this.serviceTypeFieldSpecified;
            }
            set {
                this.serviceTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool serviceChangeRequired {
            get {
                return this.serviceChangeRequiredField;
            }
            set {
                this.serviceChangeRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serviceChangeRequiredSpecified {
            get {
                return this.serviceChangeRequiredFieldSpecified;
            }
            set {
                this.serviceChangeRequiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool assocIsCancelled {
            get {
                return this.assocIsCancelledField;
            }
            set {
                this.assocIsCancelledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool assocIsCancelledSpecified {
            get {
                return this.assocIsCancelledFieldSpecified;
            }
            set {
                this.assocIsCancelledFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/commontypes")]
    public enum ServiceType {
        
        /// <remarks/>
        train,
        
        /// <remarks/>
        bus,
        
        /// <remarks/>
        ferry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/types")]
    public partial class ServiceDetails {
        
        private System.DateTime generatedAtField;
        
        private ServiceType serviceTypeField;
        
        private string locationNameField;
        
        private string crsField;
        
        private string operatorField;
        
        private string operatorCodeField;
        
        private bool isCancelledField;
        
        private string disruptionReasonField;
        
        private string overdueMessageField;
        
        private string platformField;
        
        private string staField;
        
        private string etaField;
        
        private string ataField;
        
        private string stdField;
        
        private string etdField;
        
        private string atdField;
        
        private string[] adhocAlertsField;
        
        private ArrayOfCallingPoints[] previousCallingPointsField;
        
        private ArrayOfCallingPoints[] subsequentCallingPointsField;
        
        public ServiceDetails() {
            this.isCancelledField = false;
        }
        
        /// <remarks/>
        public System.DateTime generatedAt {
            get {
                return this.generatedAtField;
            }
            set {
                this.generatedAtField = value;
            }
        }
        
        /// <remarks/>
        public ServiceType serviceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        public string crs {
            get {
                return this.crsField;
            }
            set {
                this.crsField = value;
            }
        }
        
        /// <remarks/>
        public string @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public string operatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isCancelled {
            get {
                return this.isCancelledField;
            }
            set {
                this.isCancelledField = value;
            }
        }
        
        /// <remarks/>
        public string disruptionReason {
            get {
                return this.disruptionReasonField;
            }
            set {
                this.disruptionReasonField = value;
            }
        }
        
        /// <remarks/>
        public string overdueMessage {
            get {
                return this.overdueMessageField;
            }
            set {
                this.overdueMessageField = value;
            }
        }
        
        /// <remarks/>
        public string platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        public string sta {
            get {
                return this.staField;
            }
            set {
                this.staField = value;
            }
        }
        
        /// <remarks/>
        public string eta {
            get {
                return this.etaField;
            }
            set {
                this.etaField = value;
            }
        }
        
        /// <remarks/>
        public string ata {
            get {
                return this.ataField;
            }
            set {
                this.ataField = value;
            }
        }
        
        /// <remarks/>
        public string std {
            get {
                return this.stdField;
            }
            set {
                this.stdField = value;
            }
        }
        
        /// <remarks/>
        public string etd {
            get {
                return this.etdField;
            }
            set {
                this.etdField = value;
            }
        }
        
        /// <remarks/>
        public string atd {
            get {
                return this.atdField;
            }
            set {
                this.atdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("adhocAlertText", Namespace="http://thalesgroup.com/RTTI/2012-01-13/ldb/types")]
        public string[] adhocAlerts {
            get {
                return this.adhocAlertsField;
            }
            set {
                this.adhocAlertsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("callingPointList")]
        public ArrayOfCallingPoints[] previousCallingPoints {
            get {
                return this.previousCallingPointsField;
            }
            set {
                this.previousCallingPointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("callingPointList")]
        public ArrayOfCallingPoints[] subsequentCallingPoints {
            get {
                return this.subsequentCallingPointsField;
            }
            set {
                this.subsequentCallingPointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/types")]
    public partial class ServiceLocation {
        
        private string locationNameField;
        
        private string crsField;
        
        private string viaField;
        
        private string futureChangeToField;
        
        private bool assocIsCancelledField;
        
        public ServiceLocation() {
            this.assocIsCancelledField = false;
        }
        
        /// <remarks/>
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        public string crs {
            get {
                return this.crsField;
            }
            set {
                this.crsField = value;
            }
        }
        
        /// <remarks/>
        public string via {
            get {
                return this.viaField;
            }
            set {
                this.viaField = value;
            }
        }
        
        /// <remarks/>
        public string futureChangeTo {
            get {
                return this.futureChangeToField;
            }
            set {
                this.futureChangeToField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool assocIsCancelled {
            get {
                return this.assocIsCancelledField;
            }
            set {
                this.assocIsCancelledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/types")]
    public partial class ServiceItem {
        
        private ServiceLocation[] originField;
        
        private ServiceLocation[] destinationField;
        
        private ServiceLocation[] currentOriginsField;
        
        private ServiceLocation[] currentDestinationsField;
        
        private string staField;
        
        private string etaField;
        
        private string stdField;
        
        private string etdField;
        
        private string platformField;
        
        private string operatorField;
        
        private string operatorCodeField;
        
        private bool isCircularRouteField;
        
        private string serviceIDField;
        
        private string[] adhocAlertsField;
        
        public ServiceItem() {
            this.isCircularRouteField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("location")]
        public ServiceLocation[] origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("location")]
        public ServiceLocation[] destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("location")]
        public ServiceLocation[] currentOrigins {
            get {
                return this.currentOriginsField;
            }
            set {
                this.currentOriginsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("location")]
        public ServiceLocation[] currentDestinations {
            get {
                return this.currentDestinationsField;
            }
            set {
                this.currentDestinationsField = value;
            }
        }
        
        /// <remarks/>
        public string sta {
            get {
                return this.staField;
            }
            set {
                this.staField = value;
            }
        }
        
        /// <remarks/>
        public string eta {
            get {
                return this.etaField;
            }
            set {
                this.etaField = value;
            }
        }
        
        /// <remarks/>
        public string std {
            get {
                return this.stdField;
            }
            set {
                this.stdField = value;
            }
        }
        
        /// <remarks/>
        public string etd {
            get {
                return this.etdField;
            }
            set {
                this.etdField = value;
            }
        }
        
        /// <remarks/>
        public string platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        public string @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public string operatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isCircularRoute {
            get {
                return this.isCircularRouteField;
            }
            set {
                this.isCircularRouteField = value;
            }
        }
        
        /// <remarks/>
        public string serviceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("adhocAlertText", Namespace="http://thalesgroup.com/RTTI/2012-01-13/ldb/types")]
        public string[] adhocAlerts {
            get {
                return this.adhocAlertsField;
            }
            set {
                this.adhocAlertsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2012-01-13/ldb/types")]
    public partial class NRCCMessage {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/types")]
    public partial class StationBoard {
        
        private System.DateTime generatedAtField;
        
        private string locationNameField;
        
        private string crsField;
        
        private string filterLocationNameField;
        
        private string filtercrsField;
        
        private FilterType filterTypeField;
        
        private NRCCMessage[] nrccMessagesField;
        
        private bool platformAvailableField;
        
        private bool areServicesAvailableField;
        
        private ServiceItem[] trainServicesField;
        
        private ServiceItem[] busServicesField;
        
        private ServiceItem[] ferryServicesField;
        
        public StationBoard() {
            this.filterTypeField = FilterType.to;
            this.platformAvailableField = false;
            this.areServicesAvailableField = true;
        }
        
        /// <remarks/>
        public System.DateTime generatedAt {
            get {
                return this.generatedAtField;
            }
            set {
                this.generatedAtField = value;
            }
        }
        
        /// <remarks/>
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        public string crs {
            get {
                return this.crsField;
            }
            set {
                this.crsField = value;
            }
        }
        
        /// <remarks/>
        public string filterLocationName {
            get {
                return this.filterLocationNameField;
            }
            set {
                this.filterLocationNameField = value;
            }
        }
        
        /// <remarks/>
        public string filtercrs {
            get {
                return this.filtercrsField;
            }
            set {
                this.filtercrsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(FilterType.to)]
        public FilterType filterType {
            get {
                return this.filterTypeField;
            }
            set {
                this.filterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://thalesgroup.com/RTTI/2012-01-13/ldb/types")]
        public NRCCMessage[] nrccMessages {
            get {
                return this.nrccMessagesField;
            }
            set {
                this.nrccMessagesField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool platformAvailable {
            get {
                return this.platformAvailableField;
            }
            set {
                this.platformAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool areServicesAvailable {
            get {
                return this.areServicesAvailableField;
            }
            set {
                this.areServicesAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("service")]
        public ServiceItem[] trainServices {
            get {
                return this.trainServicesField;
            }
            set {
                this.trainServicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("service")]
        public ServiceItem[] busServices {
            get {
                return this.busServicesField;
            }
            set {
                this.busServicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("service")]
        public ServiceItem[] ferryServices {
            get {
                return this.ferryServicesField;
            }
            set {
                this.ferryServicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/commontypes")]
    public enum FilterType {
        
        /// <remarks/>
        to,
        
        /// <remarks/>
        from,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetDepartureBoardCompletedEventHandler(object sender, GetDepartureBoardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartureBoardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartureBoardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StationBoard Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StationBoard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetArrivalBoardCompletedEventHandler(object sender, GetArrivalBoardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArrivalBoardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArrivalBoardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StationBoard Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StationBoard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetArrivalDepartureBoardCompletedEventHandler(object sender, GetArrivalDepartureBoardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArrivalDepartureBoardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArrivalDepartureBoardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StationBoard Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StationBoard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetServiceDetailsCompletedEventHandler(object sender, GetServiceDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceDetails)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591